### ISSUE TITLE
AEUR on chain gateway and assets

### ISSUE THREAD

**Issue by kibotmos** [mrv777/Ardor-Lite-Wallet#21]
Hi,

Please fix,
The value of AEUR is different between Chain Gateway and Assets.
The value of 1 AEUR on Assets equal to 0.0001 AEUR.

So, for example I have 1 AEUR on my wallet, then I goto Assets for exchange, and my AEUR is just 0.0001

Thanks.

**Comment by mrv777** [comment]
AEUR should not be an option for Assets, this will be removed
